In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

arr[1] = 25

print(arr)

[10 25 30 40 50]

In [2]:
import pandas as pd

In [4]:
df = pd.DataFrame()

In [5]:
df = pd.read_excel('/STUDENT.xlsx' )

In [8]:
df.tail()

,Unnamed: 0,"MANAV RACHNA INTERNATIONAL INSTITUTE OF RESEARCH AND STUDIES (DEEMED TO BE UNIVERSITY), FARIDABAD",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRADEEP KUMAR,MALE,HINDUISM,GENERAL,411928935707,8587880439,HARSHIT.MAHAL@GMAIL.COM,DELHI,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AJAYPAL SINGH,MALE,HINDUISM,GENERAL,558072965647,9891553858,DKCHAUHAN1001@GMAIL.COM,HARYANA,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PARVINDER KUMAR,MALE,HINDUISM,OBC,551216072014,9870325509,SNEHAASAINI21@GMAIL.COM,HARYANA,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NIMMAGADDA RAVIKUMAR,MALE,HINDUISM,GENERAL,400861153774,9160887585,NIMMAGADDAYASWANTH9@GMAIL.COM,ANDHRA PRADESH,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SUNIL,MALE,HINDUISM,GENERAL,298016263693,8287242495,DAKSHGANDHI22@GMAIL.COM,HARYANA,NaN,NaN,NaN,NaN

In [10]:
import pandas as pd
df = pd.DataFrame()
df = pd.read_excel('/STUDENT.xlsx' )
df.tail()

,Semester,S.No.,Branch /Course,University Registration No. (Issued by R&S Branch),Date of Admission in the Present Class/Course,Roll No.,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-SN,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-FN,Gender,Religion,Category,Aadhaar No. of Student,Updated Mobile No. of Student,Updated E-mail ID,State,Total Due Fee for Current Semester / (Previous semester if pending),Fee Paid for Current Semester / (Previous semester if pending),mentors,Unnamed: 18
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRADEEP KUMAR,MALE,HINDUISM,GENERAL,4.119289e+11,8587880439,HARSHIT.MAHAL@GMAIL.COM,DELHI,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AJAYPAL SINGH,MALE,HINDUISM,GENERAL,5.580730e+11,9891553858,DKCHAUHAN1001@GMAIL.COM,HARYANA,NaN,NaN,NaN,NaN
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PARVINDER KUMAR,MALE,HINDUISM,OBC,5.512161e+11,9870325509,SNEHAASAINI21@GMAIL.COM,HARYANA,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NIMMAGADDA RAVIKUMAR,MALE,HINDUISM,GENERAL,4.008612e+11,9160887585,NIMMAGADDAYASWANTH9@GMAIL.COM,ANDHRA PRADESH,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SUNIL,MALE,HINDUISM,GENERAL,2.980163e+11,8287242495,DAKSHGANDHI22@GMAIL.COM,HARYANA,NaN,NaN,NaN,NaN

In [12]:
import pandas as pd
df = pd.DataFrame()
df = pd.read_excel('/STUDENT.xlsx' )
df.head(5)

,Semester,S.No.,Branch /Course,University Registration No. (Issued by R&S Branch),Date of Admission in the Present Class/Course,Roll No.,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-SN,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-FN,Gender,Religion,Category,Aadhaar No. of Student,Updated Mobile No. of Student,Updated E-mail ID,State,Total Due Fee for Current Semester / (Previous semester if pending),Fee Paid for Current Semester / (Previous semester if pending),mentors,Unnamed: 18
0,5CSB1,1.0,B.Tech - Computer Science & Engineering,22/FET/0119,29.07.2024,1/22/FET/BCS/065,SNEHA SRIVASTAVA,AJIT KUMAR SRIVASTAVA,FEMALE,HINDUISM,GENERAL,6.033757e+11,9997419537,SNEHASRIVASTAVA@GMAIL.COM,UP,0,0.0,Dr MEETA SINGH,NaN
1,5CSB1,2.0,B.Tech - Computer Science & Engineering,22/FET/0120,29.07.2024,1/22/FET/BCS/066,DHRUV RAWAT,DIGPAL SINGH RAWAT,MALE,HINDUISM,GENERAL,7.805329e+11,8595742900,RDHRUVRAWAT@GMAIL.COM,HARYANA,0,0.0,Dr KANISHKA RAHEJA,NaN
2,5CSB1,3.0,B.Tech - Computer Science & Engineering,22/FET/0121,29.07.2024,1/22/FET/BCS/067,HARSHIT .,SANDEEP,MALE,HINDUISM,OBC,2.663434e+11,8800920014,YHARSHIT2204@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
3,5CSB1,4.0,B.Tech - Computer Science & Engineering,22/FET/0122,29.07.2024,1/22/FET/BCS/068,SARTHAK MONGA,DURGA SHARN MONGA,MALE,HINDUISM,GENERAL,9.875564e+11,9213742980,SARTHAKM317@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
4,5CSB1,5.0,B.Tech - Computer Science & Engineering,22/FET/0123,29.07.2024,1/22/FET/BCS/069,DHRUV KAUSHAL,RAJESH KAUSHAL,MALE,HINDUISM,GENERAL,7.802552e+11,9810934758,DHRUVKAUSHAL69@GMAIL.COM,HARYANA,0,0.0,Dr SHILPI GUPTA,NaN

In [19]:
df.rename(columns={'Branch /Course':'Course'},inplace=True)

In [20]:
df.head(5)

,Semester,S.No.,Course,University Registration No. (Issued by R&S Branch),Date of Admission in the Present Class/Course,Roll No.,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-SN,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-FN,Gender,Religion,Category,Aadhaar No. of Student,Updated Mobile No. of Student,Updated E-mail ID,State,Total Due Fee for Current Semester / (Previous semester if pending),Fee Paid for Current Semester / (Previous semester if pending),mentors,Unnamed: 18
0,5CSB1,1.0,B.Tech - Computer Science & Engineering,22/FET/0119,29.07.2024,1/22/FET/BCS/065,SNEHA SRIVASTAVA,AJIT KUMAR SRIVASTAVA,FEMALE,HINDUISM,GENERAL,6.033757e+11,9997419537,SNEHASRIVASTAVA@GMAIL.COM,UP,0,0.0,Dr MEETA SINGH,NaN
1,5CSB1,2.0,B.Tech - Computer Science & Engineering,22/FET/0120,29.07.2024,1/22/FET/BCS/066,DHRUV RAWAT,DIGPAL SINGH RAWAT,MALE,HINDUISM,GENERAL,7.805329e+11,8595742900,RDHRUVRAWAT@GMAIL.COM,HARYANA,0,0.0,Dr KANISHKA RAHEJA,NaN
2,5CSB1,3.0,B.Tech - Computer Science & Engineering,22/FET/0121,29.07.2024,1/22/FET/BCS/067,HARSHIT .,SANDEEP,MALE,HINDUISM,OBC,2.663434e+11,8800920014,YHARSHIT2204@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
3,5CSB1,4.0,B.Tech - Computer Science & Engineering,22/FET/0122,29.07.2024,1/22/FET/BCS/068,SARTHAK MONGA,DURGA SHARN MONGA,MALE,HINDUISM,GENERAL,9.875564e+11,9213742980,SARTHAKM317@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
4,5CSB1,5.0,B.Tech - Computer Science & Engineering,22/FET/0123,29.07.2024,1/22/FET/BCS/069,DHRUV KAUSHAL,RAJESH KAUSHAL,MALE,HINDUISM,GENERAL,7.802552e+11,9810934758,DHRUVKAUSHAL69@GMAIL.COM,HARYANA,0,0.0,Dr SHILPI GUPTA,NaN

In [27]:
df.rename(columns={'University Registration No. (Issued by R&S Branch)':'Registration Number'},inplace=True)

In [28]:
df.head(5)

,Semester,S.No.,Course,Registration Number,Date of Admission in the Present Class/Course,Roll No.,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-SN,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-FN,Gender,Religion,Category,Aadhaar No. of Student,Updated Mobile No. of Student,Updated E-mail ID,State,Total Due Fee for Current Semester / (Previous semester if pending),Fee Paid for Current Semester / (Previous semester if pending),mentors,Unnamed: 18
0,5CSB1,1.0,B.Tech - Computer Science & Engineering,22/FET/0119,29.07.2024,1/22/FET/BCS/065,SNEHA SRIVASTAVA,AJIT KUMAR SRIVASTAVA,FEMALE,HINDUISM,GENERAL,6.033757e+11,9997419537,SNEHASRIVASTAVA@GMAIL.COM,UP,0,0.0,Dr MEETA SINGH,NaN
1,5CSB1,2.0,B.Tech - Computer Science & Engineering,22/FET/0120,29.07.2024,1/22/FET/BCS/066,DHRUV RAWAT,DIGPAL SINGH RAWAT,MALE,HINDUISM,GENERAL,7.805329e+11,8595742900,RDHRUVRAWAT@GMAIL.COM,HARYANA,0,0.0,Dr KANISHKA RAHEJA,NaN
2,5CSB1,3.0,B.Tech - Computer Science & Engineering,22/FET/0121,29.07.2024,1/22/FET/BCS/067,HARSHIT .,SANDEEP,MALE,HINDUISM,OBC,2.663434e+11,8800920014,YHARSHIT2204@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
3,5CSB1,4.0,B.Tech - Computer Science & Engineering,22/FET/0122,29.07.2024,1/22/FET/BCS/068,SARTHAK MONGA,DURGA SHARN MONGA,MALE,HINDUISM,GENERAL,9.875564e+11,9213742980,SARTHAKM317@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
4,5CSB1,5.0,B.Tech - Computer Science & Engineering,22/FET/0123,29.07.2024,1/22/FET/BCS/069,DHRUV KAUSHAL,RAJESH KAUSHAL,MALE,HINDUISM,GENERAL,7.802552e+11,9810934758,DHRUVKAUSHAL69@GMAIL.COM,HARYANA,0,0.0,Dr SHILPI GUPTA,NaN

In [33]:
df.rename(columns={'Date of Admission in the Present Class/Course':'Admission date'},inplace=True)

In [34]:
df.head(5)

,Semester,S.No.,Course,Registration Number,admission date,Roll No.,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-SN,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-FN,Gender,Religion,Category,Aadhaar No. of Student,Updated Mobile No. of Student,Updated E-mail ID,State,Total Due Fee for Current Semester / (Previous semester if pending),Fee Paid for Current Semester / (Previous semester if pending),mentors,Unnamed: 18
0,5CSB1,1.0,B.Tech - Computer Science & Engineering,22/FET/0119,29.07.2024,1/22/FET/BCS/065,SNEHA SRIVASTAVA,AJIT KUMAR SRIVASTAVA,FEMALE,HINDUISM,GENERAL,6.033757e+11,9997419537,SNEHASRIVASTAVA@GMAIL.COM,UP,0,0.0,Dr MEETA SINGH,NaN
1,5CSB1,2.0,B.Tech - Computer Science & Engineering,22/FET/0120,29.07.2024,1/22/FET/BCS/066,DHRUV RAWAT,DIGPAL SINGH RAWAT,MALE,HINDUISM,GENERAL,7.805329e+11,8595742900,RDHRUVRAWAT@GMAIL.COM,HARYANA,0,0.0,Dr KANISHKA RAHEJA,NaN
2,5CSB1,3.0,B.Tech - Computer Science & Engineering,22/FET/0121,29.07.2024,1/22/FET/BCS/067,HARSHIT .,SANDEEP,MALE,HINDUISM,OBC,2.663434e+11,8800920014,YHARSHIT2204@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
3,5CSB1,4.0,B.Tech - Computer Science & Engineering,22/FET/0122,29.07.2024,1/22/FET/BCS/068,SARTHAK MONGA,DURGA SHARN MONGA,MALE,HINDUISM,GENERAL,9.875564e+11,9213742980,SARTHAKM317@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
4,5CSB1,5.0,B.Tech - Computer Science & Engineering,22/FET/0123,29.07.2024,1/22/FET/BCS/069,DHRUV KAUSHAL,RAJESH KAUSHAL,MALE,HINDUISM,GENERAL,7.802552e+11,9810934758,DHRUVKAUSHAL69@GMAIL.COM,HARYANA,0,0.0,Dr SHILPI GUPTA,NaN

In [35]:
df.rename(columns={'Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-SN':'Student name'}, inplace=True)

In [36]:
df.head(5)

,Semester,S.No.,Course,Registration Number,admission date,Roll No.,Student name,Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-FN,Gender,Religion,Category,Aadhaar No. of Student,Updated Mobile No. of Student,Updated E-mail ID,State,Total Due Fee for Current Semester / (Previous semester if pending),Fee Paid for Current Semester / (Previous semester if pending),mentors,Unnamed: 18
0,5CSB1,1.0,B.Tech - Computer Science & Engineering,22/FET/0119,29.07.2024,1/22/FET/BCS/065,SNEHA SRIVASTAVA,AJIT KUMAR SRIVASTAVA,FEMALE,HINDUISM,GENERAL,6.033757e+11,9997419537,SNEHASRIVASTAVA@GMAIL.COM,UP,0,0.0,Dr MEETA SINGH,NaN
1,5CSB1,2.0,B.Tech - Computer Science & Engineering,22/FET/0120,29.07.2024,1/22/FET/BCS/066,DHRUV RAWAT,DIGPAL SINGH RAWAT,MALE,HINDUISM,GENERAL,7.805329e+11,8595742900,RDHRUVRAWAT@GMAIL.COM,HARYANA,0,0.0,Dr KANISHKA RAHEJA,NaN
2,5CSB1,3.0,B.Tech - Computer Science & Engineering,22/FET/0121,29.07.2024,1/22/FET/BCS/067,HARSHIT .,SANDEEP,MALE,HINDUISM,OBC,2.663434e+11,8800920014,YHARSHIT2204@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
3,5CSB1,4.0,B.Tech - Computer Science & Engineering,22/FET/0122,29.07.2024,1/22/FET/BCS/068,SARTHAK MONGA,DURGA SHARN MONGA,MALE,HINDUISM,GENERAL,9.875564e+11,9213742980,SARTHAKM317@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN
4,5CSB1,5.0,B.Tech - Computer Science & Engineering,22/FET/0123,29.07.2024,1/22/FET/BCS/069,DHRUV KAUSHAL,RAJESH KAUSHAL,MALE,HINDUISM,GENERAL,7.802552e+11,9810934758,DHRUVKAUSHAL69@GMAIL.COM,HARYANA,0,0.0,Dr SHILPI GUPTA,NaN

In [37]:
df.rename(columns={'Spelling strictly as per Registration record in Capital Letters (Issued by R&S Branch)-FN':'Fathers name'},inplace=True)

In [38]:
df.head(3)

,Semester,S.No.,Course,Registration Number,admission date,Roll No.,Student name,Fathers name,Gender,Religion,Category,Aadhaar No. of Student,Updated Mobile No. of Student,Updated E-mail ID,State,Total Due Fee for Current Semester / (Previous semester if pending),Fee Paid for Current Semester / (Previous semester if pending),mentors,Unnamed: 18
0,5CSB1,1.0,B.Tech - Computer Science & Engineering,22/FET/0119,29.07.2024,1/22/FET/BCS/065,SNEHA SRIVASTAVA,AJIT KUMAR SRIVASTAVA,FEMALE,HINDUISM,GENERAL,6.033757e+11,9997419537,SNEHASRIVASTAVA@GMAIL.COM,UP,0,0.0,Dr MEETA SINGH,NaN
1,5CSB1,2.0,B.Tech - Computer Science & Engineering,22/FET/0120,29.07.2024,1/22/FET/BCS/066,DHRUV RAWAT,DIGPAL SINGH RAWAT,MALE,HINDUISM,GENERAL,7.805329e+11,8595742900,RDHRUVRAWAT@GMAIL.COM,HARYANA,0,0.0,Dr KANISHKA RAHEJA,NaN
2,5CSB1,3.0,B.Tech - Computer Science & Engineering,22/FET/0121,29.07.2024,1/22/FET/BCS/067,HARSHIT .,SANDEEP,MALE,HINDUISM,OBC,2.663434e+11,8800920014,YHARSHIT2204@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN

In [39]:
df.rename(columns={'Category':'Category(Gen/SC/ST/OBC)'},inplace=True)

In [40]:
df.head(3)

,Semester,S.No.,Course,Registration Number,admission date,Roll No.,Student name,Fathers name,Gender,Religion,Category(Gen/SC/ST/OBC),Aadhaar No. of Student,Updated Mobile No. of Student,Updated E-mail ID,State,Total Due Fee for Current Semester / (Previous semester if pending),Fee Paid for Current Semester / (Previous semester if pending),mentors,Unnamed: 18
0,5CSB1,1.0,B.Tech - Computer Science & Engineering,22/FET/0119,29.07.2024,1/22/FET/BCS/065,SNEHA SRIVASTAVA,AJIT KUMAR SRIVASTAVA,FEMALE,HINDUISM,GENERAL,6.033757e+11,9997419537,SNEHASRIVASTAVA@GMAIL.COM,UP,0,0.0,Dr MEETA SINGH,NaN
1,5CSB1,2.0,B.Tech - Computer Science & Engineering,22/FET/0120,29.07.2024,1/22/FET/BCS/066,DHRUV RAWAT,DIGPAL SINGH RAWAT,MALE,HINDUISM,GENERAL,7.805329e+11,8595742900,RDHRUVRAWAT@GMAIL.COM,HARYANA,0,0.0,Dr KANISHKA RAHEJA,NaN
2,5CSB1,3.0,B.Tech - Computer Science & Engineering,22/FET/0121,29.07.2024,1/22/FET/BCS/067,HARSHIT .,SANDEEP,MALE,HINDUISM,OBC,2.663434e+11,8800920014,YHARSHIT2204@GMAIL.COM,HARYANA,0,0.0,Dr MONIKA SHAH,NaN